version: '3'

services:
  postgres:
    image: postgis/postgis:15-master
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_MULTIPLE_DATABASES=hiking,users,projects
